Allow charging schedule configuration
cliviu74/wallbox pull request #37
Opened 2024-04-15 18:39 UTC by nanomad

2024-05-15 08:40 UTC, cliviu74 requested changes
Can you please document getChargerSchedules and setChargerSchedules methods in the main README.md?

2024-05-19 08:51 UTC, cliviu74 commented on wallbox/wallbox.py
> +    """
Can you please document this method in the README.md?

2024-05-20 09:33 UTC, nanomad commented
@cliviu74 done :)

2024-05-20 10:21 UTC, cliviu74 commented
Nice one, thanks a million @nanomad

2024-05-20 10:21 UTC, merged