adding "action:9" to switch back to schedule after manually pausing
cliviu74/wallbox pull request #42
Opened 2024-05-11 10:31 UTC by msftphleiten

When you run scheduled sessions, but also optimize the prizing using EPEX Spot pricing to manually start and stop charing the charger does not return back into the desired "Scheduled" state (state code 179), but stays in paused (cde 182).

with the new function you can put the charger back into the desired scheduled state as documented here: https://github.com/SKB-CGN/wallbox

2024-05-11 16:12 UTC, tmenguy commented
Fix #42

2024-05-13 17:07 UTC, cliviu74 requested changes
Looks good to me. 
Can you please add a description for this method to the README.md? [README.md](https://github.com/cliviu74/wallbox/blob/master/README.md)

2024-05-13 17:48 UTC, tmenguy commented
Cool thx for that! (I have contributed the change to https://github.com/SKB-CGN/wallbox for the action 9) We may have others because the API has added some endpoints especially to check the state of the charge to see if the command 9 is successful, strangely they are using the session object to prob it in the iOS App.

2024-05-16 12:40 UTC, Philippe59710fr commented
Great, I am looking for the same functionnality, as I need to stop the ecomode, unless my home battery keeps depleting, as the charger always sees energy available.
I will compute and send the order when needed.
I may test this addon as well if I can help

2024-05-17 16:39 UTC, tmenguy commented
> Great, I am looking for the same functionnality, as I need to stop the ecomode, unless my home battery keeps depleting, as the charger always sees energy available. I will compute and send the order when needed. I may test this addon as well if I can help

@Philippe59710fr  : this one won't allow you to stop the eco mode, it is another API, I'll probably open a PR on it too (now the API is available to set and toggle the EcosSmart mode you need), I'm just waiting for @cliviu74 to merge the 4 current PR we have. Will update the Wallbox API doc in https://github.com/SKB-CGN/wallbox too

2024-05-19 08:41 UTC, merged